sudo: false
language: rust
cache: cargo
rust:
- stable
install:
- curl -LSfs https://japaric.github.io/trust/install.sh | sh -s -- --git rust-lang-nursery/mdBook
  --crate mdbook --force --target x86_64-unknown-linux-gnu --tag v0.1.2
script:
- mdbook build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GH_TOKEN"
  local_dir: book
  target_branch: gh-pages
  on:
    branch: master
